CREATE TABLE IF NOT EXISTS EMIP_RELATION (
    RELATION_ID UUID NOT NULL, FROM_OBJECT_ID UUID NOT NULL, TO_OBJECT_ID UUID NOT NULL,
    RELATION_TYPE VARCHAR(50) NOT NULL, SOURCE_TYPE VARCHAR(50) NOT NULL, CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT EMIP_PK_RELATION PRIMARY KEY (RELATION_ID),
    CONSTRAINT EMIP_FK_RELATION_FROM FOREIGN KEY (FROM_OBJECT_ID) REFERENCES EMIP_OBJECT (OBJECT_ID),
    CONSTRAINT EMIP_FK_RELATION_TO FOREIGN KEY (TO_OBJECT_ID) REFERENCES EMIP_OBJECT (OBJECT_ID)
) DISTRIBUTED BY (RELATION_ID);
CREATE INDEX EMIP_IDX_RELATION_FROM ON EMIP_RELATION (FROM_OBJECT_ID);
CREATE INDEX EMIP_IDX_RELATION_TO ON EMIP_RELATION (TO_OBJECT_ID);
