CREATE TABLE IF NOT EXISTS EMIP_PROPERTY (
    PROPERTY_ID UUID NOT NULL,
    OBJECT_ID UUID NOT NULL,
    PROPERTY_NAME VARCHAR(200) NOT NULL,
    PROPERTY_VALUE TEXT,
    CONSTRAINT PK_EMIP_PROPERTY PRIMARY KEY (PROPERTY_ID),
    CONSTRAINT FK_EMIP_PROPERTY_OBJECT FOREIGN KEY (OBJECT_ID) REFERENCES EMIP_OBJECT (OBJECT_ID)
) DISTRIBUTED BY (PROPERTY_ID);

CREATE INDEX IX_EMIP_PROPERTY_OBJECT ON EMIP_PROPERTY (OBJECT_ID);
