CREATE TABLE IF NOT EXISTS EMIP_SOURCE_LOCATION (
    SOURCE_LOCATION_ID UUID NOT NULL,
    OBJECT_ID UUID NOT NULL,
    SOURCE_ROOT TEXT NOT NULL,
    SOURCE_FILE TEXT NOT NULL,
    SOURCE_TYPE VARCHAR(16) NOT NULL,
    START_LINE INTEGER NULL,
    END_LINE INTEGER NULL,
    START_COLUMN INTEGER NULL,
    END_COLUMN INTEGER NULL,
    CONTEXT_IDENTIFIER TEXT NULL,
    CONSTRAINT EMIP_PK_SOURCE_LOCATION PRIMARY KEY (SOURCE_LOCATION_ID),
    CONSTRAINT EMIP_FK_SOURCE_LOCATION_OBJECT FOREIGN KEY (OBJECT_ID)
        REFERENCES EMIP_OBJECT (OBJECT_ID),
    CONSTRAINT EMIP_CK_SOURCE_LOCATION_LINE_RANGE CHECK (
        START_LINE IS NULL
        OR (START_LINE > 0 AND (END_LINE IS NULL OR END_LINE >= START_LINE))
    )
)
DISTRIBUTED BY (SOURCE_LOCATION_ID);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_class AS c
        JOIN pg_namespace AS n
          ON n.oid = c.relnamespace
        WHERE n.nspname = current_schema()
          AND lower(c.relname) = lower('EMIP_IDX_SOURCE_LOCATION_OBJECT')
    ) THEN
        CREATE INDEX EMIP_IDX_SOURCE_LOCATION_OBJECT
            ON EMIP_SOURCE_LOCATION (OBJECT_ID);
    END IF;
END;
$$;
