CREATE TABLE IF NOT EXISTS EMIP_COLUMN_LINEAGE (
    LINEAGE_ID UUID NOT NULL,
    TARGET_OBJECT_ID UUID NOT NULL,
    TARGET_COLUMN_NAME VARCHAR(512) NOT NULL,
    SOURCE_OBJECT_ID UUID NULL,
    SOURCE_COLUMN_NAME VARCHAR(512) NULL,
    CLASSIFICATION VARCHAR(32) NOT NULL,
    EXPRESSION TEXT NOT NULL,
    STATEMENT_SQL TEXT NOT NULL,
    SOURCE_TYPE VARCHAR(64) NOT NULL,
    SOURCE_ROOT TEXT NULL,
    SOURCE_FILE TEXT NULL,
    SOURCE_OBJECT TEXT NOT NULL,
    EVIDENCE TEXT NOT NULL,
    UNRESOLVED_REASON VARCHAR(128) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TARGET_OBJECT_ID, LINEAGE_ID)
)
DISTRIBUTED BY (TARGET_OBJECT_ID);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'emip_idx_column_lineage_source'
          AND n.nspname = current_schema()
    ) THEN
        CREATE INDEX emip_idx_column_lineage_source
            ON EMIP_COLUMN_LINEAGE (SOURCE_OBJECT_ID);
    END IF;
END
$$;
