"""Canonical EMIP table name constants."""

OBJECT = "OBJECT"
OBJECT_VERSION = "OBJECT_VERSION"
COLUMN = "COLUMN"
COLUMN_LINEAGE = "COLUMN_LINEAGE"

RELATION = "RELATION"
SOURCE_LOCATION = "SOURCE_LOCATION"


PROPERTY = "PROPERTY"
